name: Deploy GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: npm run compile
        run: npm run compile

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: compiled-docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
